meggsimum/sauber-sdi-docker

build-and-start.sh, docker-stack.yml, postgrest/Dockerfile
PR contains several adjustment due to the first deployment on the target server.
=> Adaptions due to first deploy on target server

um_ol_demo/.dockerignore, um_ol_demo/Webmap.dockerfile, um_ol_demo/index.html
And won't create PR from master next time
=> Install OL demo deps via npm

build-and-start.sh, docker-stack.yml
=> Add um_ol_demo to Docker Stack

um_ol_demo/index.html, um_ol_demo/index.js
This PR introduces several improvements related to the OL UM demo:
- Let the demo listen to own UM channel `geotiff-demo`
- Add button to publish demo messages to `geotiff-demo` channel
- Introduces some layout improvements
=> OL UM demo improvements

build-and-start.sh
Fix and simplify build-and-start script.
=> Hotfix um server v2

docker-stack.yml, station_layer_creator/.dockerignore, station_layer_creator/.eslintrc.js, station_layer_creator/.gitignore, station_layer_creator/Dockerfile, station_layer_creator/config/config.js, station_layer_creator/cronjob/config, station_layer_creator/index.js, station_layer_creator/js-utils/docker-secrets.js, station_layer_creator/js-utils/logging.js, station_layer_creator/package-lock.json, station_layer_creator/package.json
This PR introduces a first version of a Node.js script to create DB views and the corresponding GeoServer layers for all station-pollutant combinations. Creation is based on the [fv_stations FeatureType](https://sauber-sdi.meggsimum.de/geoserver/station_data/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=station_data%3Afv_stations&maxFeatures=50&outputFormat=application%2Fjson).
/cc @jdk24
=> First version of station_layer_creator script

docker-stack.yml
Upgrade GeoServer to current latest maintenance version 2.17.4.
=> Upgrade GeoServer to version 2.17.4

build-and-start.sh, build-images.sh
Adds the new `station_layer_creator` image (introduced by #48) to the sh files `build-images.sh` and `build-and-start.sh`.
=> Add station_layer_creator image to build sh files

docker-stack.yml
Update secret bindings to latest stage.
=> Update secret binding

docker-stack.yml, geoserver_init/index.js
- set the GeoServer proxy base url via the REST-API to `https://sauber-sdi.meggsimum.de/geoserver`
- this fixes the issue that the productive GeoServer points to internal Docker services instead of the correct URL
=> Set "proxy base url" for GeoServer

json_download/src/main/java/de/meggsimum/sauber/sdi/JSONDownloader.java
Remove handling of event properties sideshow.
=> Hotfix: Update JSONDownloader

.gitignore, build-images.sh, db/Dockerfile, db/docker-entrypoint-initdb.d/010_sauber_roles.sh, db/docker-entrypoint-initdb.d/020_setup_pgrst.sh, db/resources/bin/docker-entrypoint.sh, db/update-files.d/0_test.sql, db/update-files.d/1_alter_raster_metadata.sql, db/update-files.d/2_alter_lanuv_parse.sql, db/update-files.d/3_create_component_views.sql, db/update-files.d/4_create_measurement_parsers.sql, db/update-files.d/5_create_metainfo_tables_views.sql, db/update-files.d/6_setup_pg_cron.sh, db/update-files.d/7_create_pg_cron_jobs.sql, docker-stack.yml
Depends on #64.
Add extension, add initial REFRESH MATERIALIZED VIEW job.
Rename DB service to "db", since "postgis_alpine" contains e.g. tsdb, pg_cron  as well now.
=> Add pg_cron to database instance

db/update-files.d/8_create_station_view.sql
Create fv_stations view on DB init to close issue #94.
=> Create fv_stations on db_init

geoserver_init/000_change-auth.js, geoserver_init/010_init-gs.js
Adds more logs for `geoserver_init` service in order to be able to do better debugging (in case of failures).
=> More and better logs for geoserver_init

db/update-files.d/10_view_creation_as_transaction.sql
Alter file cut off during CRLF - LF conversion
=> Fix update file cut by dos2unix

station_layer_creator/index.js
This uses the DB view creation function `station_data.create_data_views('STATION-CODE', 'POLLUTANT')`, which creates the prediction view and the measurement view for a station-pollutant-combination. The function was introduced with #108.
Also ensures that the aggregated DB views and GS layers are only tried to create if they are not already existing in the GeoServer.
Closes #92
=> Use wrapped DB view creations for stations

build-images.sh
=> Push lanuv and lubw downloader imgs to hub

docker-stack.yml, geoserver_publisher/index.js
=> Rename "postgrest_raster_publisher" to "postgrest"

station_layer_creator/cronjob/config, station_layer_creator/package.json
Optimizes the `station_layer_creator` service:
- Update node dependencies to current versions
- avoid logging into log file, so the logs appear in the service logs
=> Optimize station_layer_creator service

docker-stack.yml
Previous version: 2.19.3
Newer version: 2.20.1
=> docker-stack.yml: Update GeoServer -> 2.20.1
