meggsimum/sauber-sdi-docker

docker-stack.yml, nginx/nginx.conf
This PR adds the traffic visualization demo client, which was deployed by the previous docker-compse setup, to the current stack. Also adds a `nginx` proxy server to access the demo client and the GeoServer via port 80.
=> Add the traffic visualization demo client to the stack  

postgrest/Dockerfile
Fixes the broken build of the PostgREST image:
- Add a key to download `postgresql-server-dev-11` and `postgresql-11-pgtap`
- (tmp) remove make execution
- Correct path to config file
=> Fix build for PostgREST image

build-and-start.sh
Trying to create an existing channel will throw an error, which would be irrelevant here. If this workflow persists, we can either check for existing channels, or send error message to dev/null as well.
=> Create HeartbeatChannel on UM Server on deploy

docker-stack.yml
Fixup up for #15:  Remove `lubw_download` service from Docker stack
=> Remove 'lubw_download' from Docker stack

build-and-start.sh, build-images.sh, docker-stack.yml
This PR ensures that the Docker images in the stack are named after the published ones at hub.docker.io and that these are tied to a specific version. Thefore a the `docker-stack.yml` is adapted.
The `build-and-start.sh` is also changed that the built images are are versioned with the current date and a salt (e.g. `20200701_1`), which is the new convention.
Also adds another shell script `build-images.sh`, which only builds the images and optionally pushed them to hub.docker.io.
Removes unused service in docker-stack in order to clean up the yml file.
=> Convention based naming of Docker images 

build-and-start.sh, build-images.sh, docker-stack.yml
This ensures that the environment variable `TAG` can be used to modify the Docker image tag used for the images in the Docker stack. Default is `"master"`.
Also ensures that in the build scripts for the Docker images a tag `"master"` is set to the images.
So calling the e.g. `stack deploy` command with an env var can change the images used:
`TAG=foobar docker stack deploy -c docker-stack.yml sauber-stack`
=> Use TAG env var for Docker image tags in stack

nginx/nginx.conf
Removes traffic demo setting from nginx configuration since the demo is obsolete.
=> Remove traffic demo from nginx conf

docker-stack.yml, nginx/nginx.conf
This adds the WMS-Time WebGIS viewer based on [Wegue](https://github.com/meggsimum/wegue/) to the Docker stack.
Docker image used includes the current demo WMS-Time layer. Can be changed later on by mounting a custom config file.
=> Add WMS-Time viewer to Docker stack

docker-stack.yml, nginx/nginx.conf
This prepares the usage of SSL in the nginx-based proxy web server:
- A mount for the certificates to `/etc/ssl/certs` in the docker service is declared and the port 443 is exposed. 
- The nginx configuration for SSL usage is prepared (but commented out) since the certificates have to be in place when launching the nginx service, otherwise it fails.
=> Prepare using SSL in nginx web-proxy

build-and-start.sh
Adds a config to skip building the Docker images in `build-and-start.sh`. By executing 
```bash
./build-and-start.sh SKIPBUILD
```
the Docker image build can be deactivated.
=> Add config to skip Docker build in build-and-start.sh

.github/workflows/ci-sauber-sdi-docker.yml, build-images.sh
This adds a first CI workflow (by Github Actions), which builds all Docker images and pushes them to hub.docker ([sauberprojekt](https://hub.docker.com/u/sauberprojekt) organization). Executed on every push to the master branch. So practically due to branch protection it is only executed when a reviewed PR is merged.
Closes #38
=> Activate Github Actions for CI

docker-stack.yml
This PR disables CORS for GeoServer on application level. CORS is already handled by the nginx proxy webserver and it should be the only place to handle this. Having it enabled on both sides an error like this occurs:
```
Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
```
This might have the drawback that accessing the GeoServer directly does not supoport COIRS anymore. But accessing directly is no good idea and should not be doe anyway :stuck_out_tongue_closed_eyes: 
Fixes #55
=> Do not use CORS in GeoServer (handled by proxy instead)

docker-stack.yml
This adds the env var `GEOSERVER_CSRF_WHITELIST` to the docker service config for GeoServer. By setting the deploy domain, the GeoServer admin GUI gets fully working behind the reverse proxy. Check [here](https://docs.geoserver.org/latest/en/user/security/webadmin/csrf.html) for more information.
Fixes #58
=> Fix GeoServer admin GUI usage behind reverse proxy

build-and-start.sh
This removes the redundant image build commands in the `build-images.sh` and `build-and-start.sh` scripts. Now `build-and-start.sh` executes the `build-images.sh` if necessary. So we have to maintain the build commands only at one spot.
=> Build image cmds only in build-images.sh

raster_download/src/main/java/de/meggsimum/sauber/sdi/RasterDownloader.java
Alter raster downloader so that for every downloaded raster, it recursively searches ImageMosaic properties for the path it is referenced in. Add path of properties directory to raster_metadata table.
=> Expand raster metadata

geoserver_publisher/Dockerfile
Installs the missing 'zip' program in the `geoserver_raster_publisher` Docker Image.
Partly for #82
=> Install missing 'zip' in geoserver_raster_publisher

geoserver_publisher/cronjob/config
This ensures that the current working directory has the correct value when the `geoserver_raster_publisher` node script (`index.js`) is executed as cronjob.
=> Fix CWD in cronjob execution of 'geoserver_raster_publisher'

geoserver_init/000_change-auth.js, geoserver_init/010_init-gs.js, geoserver_init/Dockerfile, geoserver_init/package.json
This splits changing the default GeoServer credentials and initializing GeoServer data (e.g. workspaces, etc.) into separate scripts.
Otherwise once the credentials have been changed the `geoserver_init` script is not runnable anymore.
=> geoserver_init: Split change GS credentials and GS init script

docker-stack.yml
Upgrades GeoServer to current stable version 2.19.1.
Closes #78
=> Upgrade GeoServer to v2.19.1

README.md, build-and-start.sh, build-images.sh
This replaces the hard coded var 'MASTER_TAG' by the env var `TAG` in the build bash scripts. So the tag for the Docker images can be modified from outside and the `TAG` env var used in the `docker-stack.yml` can be reused.
The default is `'master' `as it was the hard coded value before, so no functional change at all (if nothing else is configured).
This allows to build and fire up the Docker stack with a consitent TAG for all Docker images by executing:
`TAG=kalle ./build-and-start.sh`
Very helpful for local dev setup or publishing all images with a dedicated tag.
=> Replace ENV VAR 'MASTER_TAG' by 'TAG' in build sh scripts

geoserver_init/010_init-gs.js, geoserver_init/package-lock.json
This adds the automatic creation of the GeoServer layer `'station_data:fv_stations'` in the `geoserver_init` service.
_Can only be merged once #94 is finalized._
Closes #95
=> Add creation of fv_stations layer in geoserver_init

docker-stack.yml
fixes #106 
The service `geoserver_init` repeatedly restarts it self. This is not required, it has to run only once, since it only initializes the GeoServer.
Adapting the `docker-stack.yml` like this fixes the problem.
```
deploy:
replicas: 1
restart_policy:
condition: on-failure
```
Removing the `deploy` tag completely did not have any effect on the continuous restarting.
=> geoserver_init: prevent repeating restart

build-and-start.sh
fixes #105 
Adapt the `build-and-start.sh` script to create the mount directories for GeoServer.
=> Run Script: create mount directories for GeoServer

db/update-files.d/11_validate_station_positions.sql, db/update-files.d/5_create_metainfo_tables_views.sql
`Edit: Split two changes into two PRS #115, #116`
Alter parser function: Check if incoming station positions are ~ within Germany.
If yes: Insert / Update station info
If no: Set coordinates NULL. If the station metadata is otherwise correct, this inserts a new station with empty coordinates. Can be updated when correct coordinates are sent. This also prevents Updating wrong coordinates for stations without coordinates so far.
C.f. [here in code](https://github.com/meggsimum/sauber-sdi-docker/compare/master...jdk24:validate_station_positions?expand=1#diff-a61de83f847f3aeff16cd56065d43ce5b2c717dbbc7e1fd96016b1d8b0ed1edaR118-R123).
This should be merged **after** #116 to prevent the parser trying to insert text into integer column.
=> Validate incoming coordinates of stations

docker-stack.yml, geoserver_init/wait-for.sh
This modifies the wait-for.sh script in the `geoserver_init` service, so it checks for a running GeoServer and a running PostgREST server in our stack. Only the it makes sense to start the init script for the GeoServer.
Fixes #133
=> Wait for GeoServer and PostgREST to start geoserver_init

build-images.sh, raster_download/Dockerfile
This ensures that the Docker image `raster_download` can be built. Since the build failed in github actions it is more than outdated in our  registry at hub.docker (see https://hub.docker.com/r/sauberprojekt/raster_download)
=> Fix build for raster_download Docker image

docker-stack.yml
Adds the secret `sauber_manager_password` into the service `geoserver_raster_publisher`, so the DB password in the `datastore.properties` can be set correctly.
=> Inject 'sauber_manager_password' secret into 'geoserver_raster_publisher

geoserver_publisher/cronjob/config, geoserver_publisher/index.js, geoserver_publisher/package-lock.json, geoserver_publisher/package.json
This adds several improvements for the `raster_publication` service:
- Enable nearest match and set acceptable interval for time dimension in the GeoServer raster layer
- Only set time dimension if not already set on the GeoServer layer
- Also enable time dimension when GeoServer layer is created (before only set, if it was existing)
- Do not log to file in cronjob, so the logs should appear in the container logs.
=> Improve raster publication service 

docker-stack-geoserver-only.yml, start-geoserver-only-stack.sh
This adds a docker stack yml file for a 'GeoServer only' dev setup. It has only the 4 related services around GeoServer in it and allows to start a lightweight stack for development around out GeoServer related components. The stack has the following services:
- **db** (The DB as data container for GeoServer)
- **geoserver** (GeoServer instance itself)
- **geoserver_init** (Initializes the GeoServer instance)
- **postgrest** (Needed for geoserver_init)
The lightweight dev stack can be started with: `docker stack deploy -c docker-stack-geoserver-only.yml sauber-stack`
Also adds a little bash script in order to start a cleaned local GeoServer only stack. **Caution: This script resets local DB and GeoServer data und should therefore only be used on local dev setups.**
=> Add docker stack yml file for GeoServer only setup

docker-stack.yml
This removes the `wms-time-viewer` service based on an outdated image from the Docker stack.
The WMS-Time demonstrator is now available under https://sauber-projekt.meggsimum.de/wms-time-viewer/?time=2021-08-26T21:00 to demonstrate the decentralized usage of our SDI.
=> Remove outdated 'wms-time-viewer' service from stack

docker-stack.yml
In order to keep the backup files in case the DB container stops working. 
Notwithstanding possible implementation of different pg_backup workflow.
=> Mount DB backups to host sys

docker-stack.yml
Now that rasters are saved as out-DB rasters in the Geoserver instance, make them accessible to the DB instance, for possible in-DB calculations. 
Read-only as no write access should be necessary, thus avoid any R/W conflicts.
=> Add access to out-DB raster data for DB

db/resources/bin/pg_backup.sh
Check if created backup is > 10MB
If not: print warning, do not trigger new wrapper function to delete outdated backups (+7 days for daily updates)
Could be expanded by checking against previous update file, however built-in busybox date tools do not support relative dates -> Would need to change Dockerfile itself.
=> Simple check for DB backup size

nginx/nginx.conf
Since the time-viewer is no more part of the stack in order to show the decentralized character of the platform the corresponding nginx config is removed with this.
=> Remove obsolete time-viewer config for nginx

docker-stack.yml, raster_download/src/main/java/de/meggsimum/sauber/sdi/RasterDownloader.java
If raster metadata contains `{"type":"sim-..."}`, publish in single coverage store -> raster layer on GeoServer instance.
The idea is to publish current and changed land use in pairs. 
Name created from 
1. `sim-current/sim-changed` prefix 
1. region
1. new parameter `{"scenario":"location_#"}`
1. pollutant 
E.g. sim_change_heidelberg_bahnhof_3_co2
=> RasterDownloader: Handle simulation rasters

docker-stack.yml
Upgrades GeoServer in the stack to latest maintenance version 2.19.3.
=> Upgrade GeoServer to version 2.19.3

geoserver_init/010_init-gs.js, geoserver_init/Dockerfile, geoserver_init/package-lock.json, geoserver_init/package.json, geoserver_init/sld/README.md, geoserver_init/sld/raster_no.sld, geoserver_init/sld/raster_no2.sld, geoserver_init/sld/raster_o3.sld, geoserver_init/sld/raster_pm10.sld, geoserver_init/sld/sim_no.sld, geoserver_init/sld/sim_no2.sld, geoserver_init/sld/sim_o3.sld, geoserver_init/sld/sim_pm10.sld, geoserver_publisher/index.js
references #145 
- adds styles for the raster layers of the GeoServer from inside `geoserver_init`
- assigns styles to the newly created image mosaics and also to image mosaics that do not have a style yet
- the respective style (`no`, `no2`, `pm10`) is chosen depending on the layer name
- it also applies styles to existing layers if they do not have a style yet
=> Add SLD styles to image mosaics

CREDITS.md
Will gladly add anything I've overlooked, plus
https://github.com/meggsimum/geoserver-docker  
and
https://github.com/meggsimum/geoserver-node-client
without a license reference if you'd like
=> Add software, license credits
